### ISSUE TITLE
Database creation

### ISSUE THREAD

**Issue by mdemarco1234** [MichalWierzbinski/cosmosdb-emulator-gremlin#3]
{"Cleanup", "g.V().drop()"},

     i run the sample and it tries to drop what appears to be the db and i get this below as an error
     
     ExceptionType : DocumentClientException
ExceptionMessage :
	Message: {"Errors":["Resource Not Found. Learn more: https:\/\/aka.ms\/cosmosdb-tsg-not-found"]}
	ActivityId: 8a450e89-7818-4ed5-ba87-d0452b0cf1ad, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: 
	RequestStartTime: 2021-05-02T16:34:47.9762642Z, RequestEndTime: 2021-05-02T16:34:47.9819098Z,  Number of regions attempted:1
	ResponseTime: 2021-05-02T16:34:47.9819098Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 22, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#22, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
	ResponseTime: 2021-05-02T16:34:47.9819098Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 22, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#22, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
	, SDK: Microsoft.Azure.Documents.Common/2.11.0, documentdb-dotnet-sdk/2.11.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0
Source : Microsoft.Azure.Documents.ClientMessage: {"Errors":["Resource Not Found. Learn more: https:\/\/aka.ms\/cosmosdb-tsg-not-found"]}
ActivityId: 8a450e89-7818-4ed5-ba87-d0452b0cf1ad, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, RequestStats: 
RequestStartTime: 2021-05-02T16:34:47.9762642Z, RequestEndTime: 2021-05-02T16:34:47.9819098Z,  Number of regions attempted:1
ResponseTime: 2021-05-02T16:34:47.9819098Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 22, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#22, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
ResponseTime: 2021-05-02T16:34:47.9819098Z, StoreResult: StorePhysicalAddress: rntbd://127.0.0.1:10251/apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/, LSN: 22, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1, ItemLSN: -1, SessionToken: -1#22, UsingLocalLSN: False, TransportException: null, ResourceType: Collection, OperationType: Read
, SDK: Microsoft.Azure.Documents.Common/2.11.0, documentdb-dotnet-sdk/2.11.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0
	BackendStatusCode : NotFound
	BackendActivityId : 8a450e89-7818-4ed5-ba87-d0452b0cf1ad
	HResult : 0x80131500
)'

**Comment by xultaeculcis** [comment]
Hi, sorry for a late reply. 

Its been over 2 years since this repo was updated last time. I am no longer maintaining it. I guess a lot has changed in those 2 years and Microsoft has introduced a breaking change of some sort (code in this repo was compatible with Emulator version 2.1.4). 

Please follow steps in [Install and use the Azure Cosmos DB Emulator for local development and testing - Gremlin API](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator?tabs=ssl-netstd21#gremlin-api) as Microsoft's documentation on Cosmos DB Emulator has improved substantially. 

Cheers!
